# Generated by Django 3.0.1 on 2020-01-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_name',
            new_name='Work',
        ),
    ]
